
export const START_EXPRESSION_REQUEST = 'START_EXPRESSION_REQUEST'
export const START_EXPRESSION_SUCCESS = 'START_EXPRESSION_SUCCESS'
export const START_EXPRESSION_FAIL = 'START_EXPRESSION_FAIL'

export const UPDATE_EXPRESSION_REQUEST = 'UPDATE_EXPRESSION_REQUEST'
export const UPDATE_EXPRESSION_SUCCESS = 'UPDATE_EXPRESSION_SUCCESS'
export const UPDATE_EXPRESSION_FAIL = 'UPDATE_EXPRESSION_FAIL'

export const EXPRESSION_STUDENT_REQUEST = 'EXPRESSION_STUDENT_REQUEST'
export const EXPRESSION_STUDENT_SUCCESS = 'EXPRESSION_STUDENT_SUCCESS'
export const EXPRESSION_STUDENT_FAIL = 'EXPRESSION_STUDENT_FAIL'
export const EXPRESSION_STUDENT_RESET = 'EXPRESSION_STUDENT_RESET'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'
