
export const START_EXPRESSION_REQUEST = 'START_EXPRESSION_REQUEST'
export const START_EXPRESSION_SUCCESS = 'START_EXPRESSION_SUCCESS'
export const START_EXPRESSION_FAIL = 'START_EXPRESSION_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
