
export const ALL_GROUPS_REQUEST = 'ALL_GROUPS_REQUEST'
export const ALL_GROUPS_SUCCESS = 'ALL_GROUPS_SUCCESS'
export const ALL_GROUPS_FAIL = 'ALL_GROUPS_FAIL'

export const NEW_GROUP_REQUEST = 'NEW_GROUP_REQUEST'
export const NEW_GROUP_SUCCESS = 'NEW_GROUP_SUCCESS'
export const NEW_GROUP_RESET = 'NEW_GROUP_RESET'
export const NEW_GROUP_FAIL = 'NEW_GROUP_FAIL'

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST'
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_RESET = 'DELETE_GROUP_RESET'
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL'

export const DELETE_GROUP_STUDENT_REQUEST = 'DELETE_GROUP_STUDENT_REQUEST'
export const DELETE_GROUP_STUDENT_SUCCESS = 'DELETE_GROUP_STUDENT_SUCCESS'
export const DELETE_GROUP_STUDENT_RESET = 'DELETE_GROUP_STUDENT_RESET'
export const DELETE_GROUP_STUDENT_FAIL = 'DELETE_GROUP_STUDENT_FAIL'

export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST'
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
export const UPDATE_GROUP_RESET = 'UPDATE_GROUP_RESET'
export const UPDATE_GROUP_FAIL = 'UPDATE_GROUP_FAIL'

export const GROUP_DETAILS_REQUEST = 'GROUP_DETAILS_REQUEST'
export const GROUP_DETAILS_SUCCESS = 'GROUP_DETAILS_SUCCESS'
export const GROUP_DETAILS_FAIL = 'GROUP_DETAILS_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'