
export const NATURESESSIONCOUR_DETAILS_REQUEST = 'NATURESESSIONCOUR_DETAILS_REQUEST'
export const NATURESESSIONCOUR_DETAILS_SUCCESS = 'NATURESESSIONCOUR_DETAILS_SUCCESS'
export const NATURESESSIONCOUR_DETAILS_FAIL = 'NATURESESSIONCOUR_DETAILS_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'