export const USERS_SESSIONCOUR_DETAILS_REQUEST = 'USERS_SESSIONCOUR_DETAILS_REQUEST'
export const USERS_SESSIONCOUR_DETAILS_SUCCESS = 'USERS_SESSIONCOUR_DETAILS_SUCCESS'
export const USERS_SESSIONCOUR_DETAILS_FAIL = 'USERS_SESSIONCOUR_DETAILS_FAIL'

export const ALL_MY_SESSIONCOURS_TEACHER_REQUEST = 'ALL_MY_SESSIONCOURS_TEACHER_REQUEST'
export const ALL_MY_SESSIONCOURS_TEACHER_SUCCESS = 'ALL_MY_SESSIONCOURS_TEACHER_SUCCESS'
export const ALL_MY_SESSIONCOURS_TEACHER_FAIL = 'ALL_MY_SESSIONCOURS_TEACHER_FAIL'

export const UPDATE_SESSIONCOUR_STATUS_REQUEST = 'UPDATE_SESSIONCOUR_STATUS_REQUEST'
export const UPDATE_SESSIONCOUR_STATUS_SUCCESS = 'UPDATE_SESSIONCOUR_STATUS_SUCCESS'
export const UPDATE_SESSIONCOUR_STATUS_RESET = 'UPDATE_SESSIONCOUR_STATUS_RESET'
export const UPDATE_SESSIONCOUR_STATUS_FAIL = 'UPDATE_SESSIONCOUR_STATUS_FAIL'


export const NEW_SESSIONCOUR_REQUEST = 'NEW_SESSIONCOUR_REQUEST'
export const NEW_SESSIONCOUR_SUCCESS = 'NEW_SESSIONCOUR_SUCCESS'
export const NEW_SESSIONCOUR_RESET = 'NEW_SESSIONCOUR_RESET'
export const NEW_SESSIONCOUR_FAIL = 'NEW_SESSIONCOUR_FAIL'


export const AVAILABLESESSIONCOURS_STUDENT_REQUEST = 'AVAILABLESESSIONCOURS_STUDENT_REQUEST'
export const AVAILABLESESSIONCOURS_STUDENT_SUCCESS = 'AVAILABLESESSIONCOURS_STUDENT_SUCCESS'
export const AVAILABLESESSIONCOURS_STUDENT_FAIL = 'AVAILABLESESSIONCOURS_STUDENT_FAIL'

export const HISTORYSESSIONCOURS_STUDENT_REQUEST = 'HISTORYSESSIONCOURS_STUDENT_REQUEST'
export const HISTORYSESSIONCOURS_STUDENT_SUCCESS = 'HISTORYSESSIONCOURS_STUDENT_SUCCESS'
export const HISTORYSESSIONCOURS_STUDENT_FAIL = 'HISTORYSESSIONCOURS_STUDENT_FAIL'

export const INFOSESSIONCOUR_STUDENT_REQUEST = 'INFOSESSIONCOUR_STUDENT_REQUEST'
export const INFOSESSIONCOUR_STUDENT_SUCCESS = 'INFOSESSIONCOUR_STUDENT_SUCCESS'
export const INFOSESSIONCOUR_STUDENT_FAIL = 'INFOSESSIONCOUR_STUDENT_FAIL'

export const SESSIONNOACTIVE_STUDENT_TEACHER_REQUEST = 'SESSIONNOACTIVE_STUDENT_TEACHER_REQUEST'
export const SESSIONNOACTIVE_STUDENT_TEACHER_SUCCESS = 'SESSIONNOACTIVE_STUDENT_TEACHER_SUCCESS'
export const SESSIONNOACTIVE_STUDENT_TEACHER_FAIL = 'SESSIONNOACTIVE_STUDENT_TEACHER_FAIL'

export const DELETE_SESSIONCOUR_REQUEST = 'DELETE_SESSIONCOUR_REQUEST'
export const DELETE_SESSIONCOUR_SUCCESS = 'DELETE_SESSIONCOUR_SUCCESS'
export const DELETE_SESSIONCOUR_RESET = 'DELETE_SESSIONCOUR_RESET'
export const DELETE_SESSIONCOUR_FAIL = 'DELETE_SESSIONCOUR_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'